# This is an example of config file.
# Copy it to `$HOME/monocular/config/monocular.yaml` in order to make the backend pick up the overrides.
repos:
  # Official repositories
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
    source: https://github.com/kubernetes/charts/tree/master/stable
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com
    source: https://github.com/kubernetes/charts/tree/master/incubator

# Enables Helm deployment integration
# https://github.com/helm/monocular/tree/master/deployment/monocular#other-configuration-options
releasesEnabled: true
# Enables port forwarding for tiller Connections
# Useful if you are running the app outside of the k8s cluster during development
tillerPortForward: true

# Specify a different namespace where to locate tiller-deploy
tillerNamespace: kube-system

# Specify a custom host for Tiller
tillerHost: localhost:30827

# Configure cache refresh interval in sec
cacheRefreshInterval: 3600

# Configure Redis server
redis:
  host: redis:6379

mongodb:
  url: mongodb:27017
  database: monocular
