# This is an example of config file.
# Copy it to `$HOME/monocular/config/monocular.yaml` in order to make the backend pick up the overrides.
repos:
  # Official repositories
  - name: stable
    url: https://aliacs-app-catalog.oss-cn-hangzhou.aliyuncs.com/charts/
    source: https://aliacs-app-catalog.oss-cn-hangzhou.aliyuncs.com/charts/
  - name: incubator
    url: https://aliacs-app-catalog.oss-cn-hangzhou.aliyuncs.com/charts-incubator/
    source: https://aliacs-app-catalog.oss-cn-hangzhou.aliyuncs.com/charts-incubator/
  # Add your own repository
  #- name: my-repo-name
  #  url: my-repository-url
  #  source: my-repository-source

# cors:
#   allowed_origins:
#     - my-ui-hostname
#   allowed_headers:
#     - "content-type"
#     - "x-xsrf-token"

# Enables Helm deployment integration
# https://github.com/helm/monocular/tree/master/deployment/monocular#other-configuration-options
releasesEnabled: true
# Enables port forwarding for tiller Connections
# Useful if you are running the app outside of the k8s cluster during development
tillerPortForward: true

useTLS: true
# Specify a different namespace where to locate tiller-deploy
tillerNamespace: kube-system

# Specify a custom host for Tiller
tillerHost: 192.168.31.222:30827

# Configure cache refresh interval in sec
cacheRefreshInterval: 3600

# Configure Redis server
redis:
  host: redis:6379

mongodb:
  url: mongodb:27017
  database: monocular
